{{ config (
    materialized = 'view'
) }}
{{ streamline_external_table_FR_query_v2(
    model = 'transactions_tdl',
    partition_function = "SPLIT_PART(SPLIT_PART(file_name, '/', 3), '=', 2) ",
    partition_name = "block_date",
    other_cols = "COMPUTE_SUCCESS,TOTAL_FEES,ORIG_STATUS,COMPUTE_SKIPPED,COMPUTE_GAS_FEES,ACTION_RESULT_CODE,DESTROYED,ACTION_SUCCESS,COMPUTE_MSG_STATE_USED,IS_TOCK,ACCOUNT_STATE_HASH_AFTER,ACTION_SPEC_ACTIONS,DESCR,ACCOUNT_STATE_BALANCE_BEFORE,HASH,ACTION_RESULT_ARG,ABORTED,MC_BLOCK_SEQNO,COMPUTE_ACCOUNT_ACTIVATED,ACTION_SKIPPED_ACTIONS,NOW,CREDIT_DUE_FEES_COLLECTED,BLOCK_SHARD,END_STATUS,CREDIT_FIRST,PREV_TRANS_HASH,BLOCK_WORKCHAIN,ACCOUNT,COMPUTE_VM_STEPS,STORAGE_FEES_COLLECTED,COMPUTE_EXIT_ARG,ACTION_VALID,ACTION_STATUS_CHANGE,INSTALLED,PREV_TRANS_LT,COMPUTE_GAS_CREDIT,COMPUTE_GAS_LIMIT,SKIPPED_REASON,ACTION_TOTAL_FWD_FEES,ACCOUNT_STATE_CODE_HASH_BEFORE,ACCOUNT_STATE_HASH_BEFORE,COMPUTE_EXIT_CODE,TRACE_ID,BLOCK_SEQNO,STORAGE_STATUS_CHANGE,LT,COMPUTE_MODE,CREDIT,STORAGE_FEES_DUE,COMPUTE_GAS_USED,ACCOUNT_STATE_CODE_HASH_AFTER,ACTION_TOTAL_ACTION_FEES,COMPUTE_VM_INIT_STATE_HASH,ACCOUNT_STATE_BALANCE_AFTER,ACTION_TOT_ACTIONS,COMPUTE_VM_FINAL_STATE_HASH,ACTION_NO_FUNDS"
) }}
