{{ config (
    materialized = 'view'
) }}
{{ streamline_external_table_query_v2(
    model = 'blocks_tdl',
    partition_function = "SPLIT_PART(SPLIT_PART(file_name, '/', 3), '=', 2) ",
    partition_name = "block_date",
    other_cols = "VERSION,CREATED_BY,END_LT,WANT_MERGE,GEN_UTIME,TX_COUNT,GLOBAL_ID,ROOT_HASH,KEY_BLOCK,MC_BLOCK_SEQNO,VERT_SEQNO_INCR,VALIDATOR_LIST_HASH_SHORT,AFTER_MERGE,WANT_SPLIT,AFTER_SPLIT,MASTER_REF_SEQNO,MC_BLOCK_WORKCHAIN,FILE_HASH,PREV_KEY_BLOCK_SEQNO,SHARD,SEQNO,VERT_SEQNO,FLAGS,RAND_SEED,GEN_CATCHAIN_SEQNO,MIN_REF_MC_SEQNO,START_LT,MC_BLOCK_SHARD,BEFORE_SPLIT,WORKCHAIN"
) }}
