version: 2

sources:
  - name: bronze_streamline
    database: streamline
    schema: ton 
    # "{{ 'ton' if target.database == 'TON' else 'ton_dev' }}"
    tables:
      - name: account_states_tdl
      - name: balances_history_tdl
      - name: blocks_tdl
      - name: dex_pools_tdl
      - name: dex_trades_tdl
      - name: jetton_events_tdl
      - name: jetton_metadata_tdl
      - name: messages_tdl
      - name: messages_with_data_tdl
      - name: nft_events_tdl
      - name: nft_items_tdl
      - name: nft_metadata_tdl
      - name: nft_sales_tdl
      - name: nft_transfers_tdl
      - name: transactions_tdl
      - name: shards
      - name: blocks
      - name: transactions
 
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'TON' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: address_tags
      - name: dim_dates
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'TON' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: number_sequence
      - name: labels_combined
      - name: complete_native_asset_metadata
      - name: complete_native_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_token_asset_metadata
      - name: complete_token_prices