{{ config (
    materialized = 'view'
) }}
{{ streamline_external_table_FR_query_v2(
    model = 'nft_events_tdl',
    partition_function = "TO_DATE(SPLIT_PART(SPLIT_PART(file_name, '/', 3), '=', 2), 'YYYYMMDD')",
    partition_name = "block_date",
    other_cols = "SALE_PRICE,ROYALTY_ADDRESS,PAYMENT_ASSET,MARKETPLACE_FEE_ADDRESS,OWNER_ADDRESS,COLLECTION_ADDRESS,CONTENT_ONCHAIN,TRACE_ID,SALE_CONTRACT,FORWARD_AMOUNT,NFT_ITEM_INDEX,QUERY_ID,IS_INIT,TIMESTAMP,NFT_ITEM_ADDRESS,CUSTOM_PAYLOAD,COMMENT,SALE_END_TIME,SALE_TYPE,AUCTION_MAX_BID,AUCTION_MIN_BID,MARKETPLACE_ADDRESS,FORWARD_PAYLOAD,ROYALTY_AMOUNT,AUCTION_MIN_STEP,TYPE,PREV_OWNER,TX_HASH,MARKETPLACE_FEE,LT"
) }}
